name: Deploy Frontend and Backend to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  # 1. Definimos los nombres de ambos repositorios de ECR
  ECR_FRONTEND_REPO: todolist
  ECR_BACKEND_REPO: todoback

jobs:
  deploy:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    # Si decidiste usar un environment, descomenta la siguiente línea:
    # environment: production  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -----------------------------------------------------------
    # PASO PARA EL FRONTEND
    # -----------------------------------------------------------
    - name: Build, tag, and push FRONTEND image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        # Construimos apuntando al Dockerfile de frontend y usando esa carpeta como contexto
        docker build \
          -t $ECR_REGISTRY/$ECR_FRONTEND_REPO:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest \
          -f frontend/Dockerfile ./frontend
        
        # Subimos el Frontend
        docker push $ECR_REGISTRY/$ECR_FRONTEND_REPO:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest

    # -----------------------------------------------------------
    # PASO PARA EL BACKEND
    # -----------------------------------------------------------
    - name: Build, tag, and push BACKEND image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        # Construimos apuntando al Dockerfile de backend y usando esa carpeta como contexto
        docker build \
          -t $ECR_REGISTRY/$ECR_BACKEND_REPO:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_BACKEND_REPO:latest \
          -f backend/Dockerfile ./backend
        
        # Subimos el Backend
        docker push $ECR_REGISTRY/$ECR_BACKEND_REPO:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_BACKEND_REPO:latest
